// <auto-generated />
using System;
using HoslaBotApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoslaBotApi.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230809235415_addColumnCommnt")]
    partial class addColumnCommnt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HoslaBotApi.Models.User", b =>
                {
                    b.Property<int>("CMS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CMS_ID"));

                    b.Property<int?>("Anger_Score")
                        .HasColumnType("int");

                    b.Property<int?>("Anxiety_Score")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Depression_Score")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Selfesteem_Score")
                        .HasColumnType("int");

                    b.HasKey("CMS_ID");

                    b.ToTable("C3A");
                });
#pragma warning restore 612, 618
        }
    }
}
